var app = new Vue({
  el: '#app',
  data: {
    filter: {
      element: [
        {
          name: '火',
          class: 'element1',
          active: true
        },
        {
          name: '水',
          class: 'element2',
          active: true
        },
        {
          name: '土',
          class: 'element3',
          active: true
        },
        {
          name: '風',
          class: 'element4',
          active: true
        },
        {
          name: '光',
          class: 'element5',
          active: true
        },
        {
          name: '暗',
          class: 'element6',
          active: true
        },
      ],
      get: [
        '恒常',
        'Fes限',
        '季節限定',
        '十天眾',
        '十賢者',
        '活動',
        '特別'
      ],
      race: [
        {
          name: '人族',
          class: 'race1'
        },
        {
          name: '獸耳',
          class: 'race2'
        },
        {
          name: '牛族',
          class: 'race3'
        },
        {
          name: '矮人',
          class: 'race4'
        },
        {
          name: '星晶獸',
          class: 'race5'
        },
        {
          name: '不明',
          class: 'race6'
        }
      ],
      weapon: [       
        {
          name: '劍',
          class: 'weapon1'
        },       
        {
          name: '短劍',
          class: 'weapon2'
        },       
        {
          name: '槍',
          class: 'weapon3'
        },       
        {
          name: '斧',
          class: 'weapon4'
        },       
        {
          name: '杖',
          class: 'weapon5'
        },       
        {
          name: '銃',
          class: 'weapon6'
        },       
        {
          name: '格鬥',
          class: 'weapon7'
        },       
        {
          name: '弓',
          class: 'weapon8'
        },
        {
          name: '樂器',
          class: 'weapon9'
        },       
        {
          name: '刀',
          class: 'weapon10'
        },
      ],
      type: [
        {
          name: '平衡',
          class: 'type1',
        },    
        {
          name: '攻擊',
          class: 'type2',
        },
        {
          name: '防禦',
          class: 'type3',
        },
        {
          name: '回復',
          class: 'type4',
        },
        {
          name: '特殊',
          class: 'type5',
        },
      ],
      gender: [
        {
          name: '男',
          src: ''
        },
        {
          name: '女',
          src: ''
        }
      ],
    },
    filted: {
      get: '',
      race:'',
      weapon:'',
      type:'',
      gender:''
    },
    chara: [
      {
        name: 'ネツァワルピリ',
        element: '風',
        race: '人族',
        weapon: ['槍'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040003000_01.jpg',
      },
      {
        name: 'レ・フィーエ',
        element: '光',
        race: '人族',
        weapon: ['劍'],
        type: '回復',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040004000_01.jpg',
      },
      {
        name: 'レディ・グレイ',
        element: '暗',
        race: '人族',
        weapon: ['槍','格鬥'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040005000_01.jpg',
      },
      {
        name: 'リリィ',
        element: '水',
        race: '不明',
        weapon: ['杖'],
        type: '回復',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040007000_01.jpg',
      },
      {
        name: 'アレーティア',
        element: '土',
        race: '人族',
        weapon: ['劍','刀'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040002000_01.jpg',
      },
      {
        name: 'ガウェイン',
        element: '風',
        race: '人族',
        weapon: ['斧'],
        type: '防禦',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040000000_01.jpg',
      },
      {
        name: 'ユエル',
        element: '火',
        race: '獸耳',
        weapon: ['劍','刀'],
        type: '平衡',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040006000_01.jpg',
      },
      {
        name: 'アルタイル',
        element: '水',
        race: '人族',
        weapon: ['杖'],
        type: '平衡',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040001000_01.jpg',
      },
      {
        name: 'サルナーン(光)',
        element: '光',
        race: '獸耳',
        weapon: ['杖'],
        type: '特殊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040008000_01.jpg',
      },
      {
        name: 'カリオストロ',
        element: '土',
        race: '人族',
        weapon: ['杖'],
        type: '回復',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040009000_01.jpg',
      },
      {
        name: 'シャルロッテ',
        element: '水',
        race: '矮人',
        weapon: ['劍'],
        type: '平衡',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040010000_01.jpg',
      },
      {
        name: 'マギサ',
        element: '火',
        race: '人族',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040011000_01.jpg',
      },
      {
        name: 'メーテラ',
        element: '風',
        race: '獸耳',
        weapon: ['弓'],
        type: '平衡',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040012000_01.jpg',
      },
      {
        name: 'セルエル',
        element: '光',
        race: '獸耳',
        weapon: ['劍'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040013000_01.jpg',
      },
      {
        name: 'レ・フィーエ(水着)',
        element: '光',
        race: '獸耳',
        weapon: ['劍'],
        type: '回復',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040014000_01.jpg',
      },
      {
        name: 'イオ(水着)',
        element: '火',
        race: '人族',
        weapon: ['杖'],
        type: '攻擊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040015000_01.jpg',
      },
      {
        name: 'ケルベロス',
        element: '暗',
        race: '星晶獸',
        weapon: ['格鬥'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040016000_01.jpg',
      },
      {
        name: 'アギエルバ',
        element: '火',
        race: '牛族',
        weapon: ['劍'],
        type: '防禦',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040017000_01.jpg',
      },
      {
        name: 'クリスティーナ	',
        element: '風',
        race: '人族',
        weapon: ['短劍','銃'],
        type: '平衡',
        gender: '女',
        get: '特別',
        show: true,
        own: false,
        img: 'img/3040018000_01.jpg',
      },
      {
        name: 'アルルメイヤ',
        element: '土',
        race: '矮人',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040019000_01.jpg',
      },
      {
        name: 'シャルロッテ(ハロウィン)',
        element: '光',
        race: '矮人',
        weapon: ['劍'],
        type: '回復',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040020000_01.jpg',
      },
      {
        name: 'レナ',
        element: '風',
        race: '人族',
        weapon: ['杖'],
        type: '回復',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040021000_01.jpg',
      },
      {
        name: 'メルゥ',
        element: '土',
        race: '獸耳',
        weapon: ['槍','斧'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040022000_01.jpg',
      },
      {
        name: 'ランスロット',
        element: '水',
        race: '人族',
        weapon: ['劍','短劍'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040023000_01.jpg',
      },
      {
        name: 'ソフィア',
        element: '光',
        race: '人族',
        weapon: ['杖'],
        type: '回復',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040024000_01.jpg',
      },
      {
        name: 'ロゼッタ(クリスマス)',
        element: '暗',
        race: '星晶獸',
        weapon: ['短劍'],
        type: '回復',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040026000_01.jpg',
      },
      {
        name: 'アニラ',
        element: '火',
        race: '牛族',
        weapon: ['槍','格鬥'],
        type: '平衡',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040027000_01.jpg',
      },
      {
        name: 'ゼタ',
        element: '火',
        race: '人族',
        weapon: ['槍'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040028000_01.jpg',
      },
      {
        name: 'バザラガ',
        element: '暗',
        race: '牛族',
        weapon: ['斧'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040029000_01.jpg',
      },
      {
        name: 'ジャンヌダルク(光)',
        element: '光',
        race: '人族',
        weapon: ['槍'],
        type: '平衡',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040040000_01.jpg',
      },
      {
        name: 'ジークフリート',
        element: '土',
        race: '人族',
        weapon: ['劍','刀'],
        type: '特殊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040025000_01.jpg',
      },
      {
        name: 'サラ',
        element: '土',
        race: '人族',
        weapon: ['格鬥'],
        type: '防禦',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040041000_01.jpg',
      },
      {
        name: 'カルメリーナ',
        element: '風',
        race: '牛族',
        weapon: ['短劍'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040042000_01.jpg',
      },
      {
        name: 'ヴィーラ',
        element: '暗',
        race: '人族',
        weapon: ['劍'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040043000_01.jpg',
      },
      {
        name: 'ソシエ',
        element: '水',
        race: '獸耳',
        weapon: ['格鬥'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040044000_01.jpg',
      },
      {
        name: 'アルベール',
        element: '光',
        race: '人族',
        weapon: ['劍'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040045000_01.jpg',
      },
      {
        name: 'クラリス',
        element: '火',
        race: '人族',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040046000_01.jpg',
      },
      {
        name: 'ウーノ',
        element: '水',
        race: '矮人',
        weapon: ['槍'],
        type: '防禦',
        gender: '男',
        get: '十天眾',
        show: true,
        own: false,
        img: 'img/3040030000_01.jpg',
      },
      {
        name: 'ソーン',
        element: '光',
        race: '人族',
        weapon: ['弓'],
        type: '平衡',
        gender: '女',
        get: '十天眾',
        show: true,
        own: false,
        img: 'img/3040031000_01.jpg',
      },
      {
        name: 'サラーサ',
        element: '土',
        race: '牛族',
        weapon: ['劍','斧'],
        type: '攻擊',
        gender: '女',
        get: '十天眾',
        show: true,
        own: false,
        img: 'img/3040032000_01.jpg',
      },
      {
        name: 'カトル',
        element: '水',
        race: '獸耳',
        weapon: ['短劍'],
        type: '特殊',
        gender: '男',
        get: '十天眾',
        show: true,
        own: false,
        img: 'img/3040033000_01.jpg',
      },
      {
        name: 'フュンフ',
        element: '光',
        race: '矮人',
        weapon: ['杖'],
        type: '回復',
        gender: '女',
        get: '十天眾',
        show: true,
        own: false,
        img: 'img/3040034000_01.jpg',
      },
      {
        name: 'シス',
        element: '暗',
        race: '獸耳',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '男',
        get: '十天眾',
        show: true,
        own: false,
        img: 'img/3040035000_01.jpg',
      },
      {
        name: 'シエテ',
        element: '風',
        race: '人族',
        weapon: ['劍'],
        type: '攻擊',
        gender: '男',
        get: '十天眾',
        show: true,
        own: false,
        img: 'img/3040036000_01.jpg',
      },
      {
        name: 'オクトー',
        element: '土',
        race: '牛族',
        weapon: ['刀'],
        type: '攻擊',
        gender: '男',
        get: '十天眾',
        show: true,
        own: false,
        img: 'img/3040037000_01.jpg',
      },
      {
        name: 'ニオ',
        element: '風',
        race: '矮人',
        weapon: ['樂器'],
        type: '特殊',
        gender: '女',
        get: '十天眾',
        show: true,
        own: false,
        img: 'img/3040038000_01.jpg',
      },
      {
        name: 'エッセル',
        element: '火',
        race: '獸耳',
        weapon: ['銃'],
        type: '平衡',
        gender: '女',
        get: '十天眾',
        show: true,
        own: false,
        img: 'img/3040039000_01.jpg',
      },
      {
        name: 'ペトラ',
        element: '風',
        race: '人族',
        weapon: ['杖'],
        type: '平衡',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040047000_01.jpg',
      },
      {
        name: 'サルナーン(暗)',
        element: '暗',
        race: '獸耳',
        weapon: ['杖'],
        type: '特殊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040048000_01.jpg',
      },
      {
        name: 'シルヴァ',
        element: '水',
        race: '人族',
        weapon: ['銃'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040049000_01.jpg',
      },
      {
        name: 'パーシヴァル',
        element: '火',
        race: '人族',
        weapon: ['劍'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040050000_01.jpg',
      },
      {
        name: 'アーミラ',
        element: '光',
        race: '不明',
        weapon: ['格鬥'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040051000_01.jpg',
      },
      {
        name: 'ガンダゴウザ',
        element: '火',
        race: '牛族',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040052000_01.jpg',
      },
      {
        name: 'カタリナ',
        element: '水',
        race: '人族',
        weapon: ['劍'],
        type: '平衡',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040054000_01.jpg',
      },
      {
        name: 'ヴィーラ(水着)',
        element: '土',
        race: '人族',
        weapon: ['劍'],
        type: '特殊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040053000_01.jpg',
      },
      {
        name: 'ダヌア(水着)',
        element: '暗',
        race: '牛族',
        weapon: ['短劍'],
        type: '特殊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040055000_01.jpg',
      },
      {
        name: 'ゼタ(水着)',
        element: '光',
        race: '人族',
        weapon: ['槍'],
        type: '攻擊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040056000_01.jpg',
      },
      {
        name: 'ヴァンピィ',
        element: '暗',
        race: '不明',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040057000_01.jpg',
      },
      {
        name: 'アンリエット',
        element: '風',
        race: '人族',
        weapon: ['樂器'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040058000_01.jpg',
      },
      {
        name: 'ラカム',
        element: '火',
        race: '人族',
        weapon: ['銃'],
        type: '特殊',
        gender: '男',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040059000_01.jpg',
      },
      {
        name: 'ヘルエス',
        element: '火',
        race: '獸耳',
        weapon: ['槍'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040060000_01.jpg',
      },
      {
        name: 'フィーナ',
        element: '風',
        race: '人族',
        weapon: ['弓'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040061000_01.jpg',
      },
      {
        name: 'カリオストロ(ハロウィン)',
        element: '暗',
        race: '人族',
        weapon: ['杖'],
        type: '平衡',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040062000_01.jpg',
      },
      {
        name: 'ナルメア',
        element: '暗',
        race: '牛族',
        weapon: ['刀'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040063000_01.jpg',
      },
      {
        name: 'ヨダルラーハ',
        element: '水',
        race: '矮人',
        weapon: ['劍','刀'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040064000_01.jpg',
      },
      {
        name: 'イオ',
        element: '光',
        race: '人族',
        weapon: ['杖'],
        type: '平衡',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040065000_01.jpg',
      },
      {
        name: 'リルル',
        element: '水',
        race: '矮人',
        weapon: ['樂器'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040066000_01.jpg',
      },
      {
        name: 'クラリス(クリスマス)',
        element: '土',
        race: '人族',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040067000_01.jpg',
      },
      {
        name: 'ロゼッタ',
        element: '風',
        race: '星晶獸',
        weapon: ['短劍'],
        type: '特殊',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040068000_01.jpg',
      },
      {
        name: 'ユーステス',
        element: '土',
        race: '獸耳',
        weapon: ['銃'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040069000_01.jpg',
      },
      {
        name: 'ベアトリクス',
        element: '暗',
        race: '人族',
        weapon: ['劍'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040070000_01.jpg',
      },
      {
        name: 'アンチラ',
        element: '風',
        race: '獸耳',
        weapon: ['杖','格鬥'],
        type: '平衡',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040071000_01.jpg',
      },
      {
        name: 'メーテラ(火)',
        element: '火',
        race: '獸耳',
        weapon: ['弓'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040072000_01.jpg',
      },
      {
        name: 'フェリ',
        element: '光',
        race: '獸耳',
        weapon: ['短劍'],
        type: '平衡',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040073000_01.jpg',
      },
      {
        name: 'キャサリン',
        element: '土',
        race: '獸耳',
        weapon: ['銃'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040074000_01.jpg',
      },
      {
        name: 'オイゲン',
        element: '土',
        race: '人族',
        weapon: ['銃'],
        type: '攻擊',
        gender: '男',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040077000_01.jpg',
      },
      {
        name: 'ゾーイ',
        element: '光',
        race: '星晶獸',
        weapon: ['劍'],
        type: '平衡',
        gender: '女',
        get: '特別',
        show: true,
        own: false,
        img: 'img/3040078000_01.jpg',
      },
      {
        name: 'ザルハメリナ',
        element: '火',
        race: '矮人',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040075000_01.jpg',
      },
      {
        name: 'アオイドス',
        element: '火',
        race: '人族',
        weapon: ['劍','樂器'],
        type: '特殊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040076000_01.jpg',
      },
      {
        name: 'ハレゼナス',
        element: '土',
        race: '牛族',
        weapon: ['斧'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040079000_01.jpg',
      },
      {
        name: 'ジャンヌダルク(暗)',
        element: '暗',
        race: '人族',
        weapon: ['劍'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040080000_01.jpg',
      },
      {
        name: 'コルワ',
        element: '風',
        race: '獸耳',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040081000_01.jpg',
      },
      {
        name: '黒騎士',
        element: '暗',
        race: '人族',
        weapon: ['劍','銃'],
        type: '攻擊',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040082000_01.jpg',
      },
      {
        name: 'アリーザ',
        element: '火',
        race: '牛族',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040083000_01.jpg',
      },
      {
        name: 'アイル',
        element: '土',
        race: '人族',
        weapon: ['格鬥'],
        type: '特殊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040084000_01.jpg',
      },
      {
        name: 'ネモネ',
        element: '土',
        race: '獸耳',
        weapon: ['斧','槍'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040085000_01.jpg',
      },
      {
        name: 'フォルテ',
        element: '暗',
        race: '牛族',
        weapon: ['槍'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040086000_01.jpg',
      },
      {
        name: 'ロザミア',
        element: '光',
        race: '人族',
        weapon: ['劍'],
        type: '平衡',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040087000_01.jpg',
      },
      {
        name: 'イングヴェイ',
        element: '水',
        race: '人族',
        weapon: ['格鬥','銃'],
        type: '防禦',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040088000_01.jpg',
      },
      {
        name: 'ナルメア(水着)',
        element: '水',
        race: '牛族',
        weapon: ['刀'],
        type: '攻擊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040089000_01.jpg',
      },
      {
        name: 'パーシヴァル(水着)',
        element: '火',
        race: '人族',
        weapon: ['劍'],
        type: '平衡',
        gender: '男',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040090000_01.jpg',
      },
      {
        name: 'ヘルエス(水着)',
        element: '光',
        race: '獸耳',
        weapon: ['槍'],
        type: '平衡',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040091000_01.jpg',
      },
      {
        name: 'ゾーイ(水着)',
        element: '暗',
        race: '星晶獸',
        weapon: ['劍'],
        type: '特殊',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040092000_01.jpg',
      },
      {
        name: 'シャノワール',
        element: '水',
        race: '人族',
        weapon: ['杖','短劍'],
        type: '特殊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040093000_01.jpg',
      },
      {
        name: 'ソシエ(火)',
        element: '火',
        race: '獸耳',
        weapon: ['格鬥'],
        type: '防禦',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040095000_01.jpg',
      },
      {
        name: 'ヴァイト',
        element: '暗',
        race: '不明',
        weapon: ['短劍'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040094000_01.jpg',
      },
      {
        name: 'ジュリエット',
        element: '光',
        race: '人族',
        weapon: ['槍'],
        type: '防禦',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040096000_01.jpg',
      },
      {
        name: 'ロミオ',
        element: '水',
        race: '人族',
        weapon: ['劍'],
        type: '平衡',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040098000_01.jpg',
      },
      {
        name: 'ユーステス(ハロウィン)',
        element: '土',
        race: '獸耳',
        weapon: ['銃'],
        type: '攻擊',
        gender: '男',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040099000_01.jpg',
      },
      {
        name: 'イシュミール',
        element: '水',
        race: '牛族',
        weapon: ['劍'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040100000_01.jpg',
      },
      {
        name: 'リーシャル',
        element: '風',
        race: '人族',
        weapon: ['劍'],
        type: '平衡',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040101000_01.jpg',
      },
      {
        name: 'メリッサベルル',
        element: '風',
        race: '矮人',
        weapon: ['劍'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040102000_01.jpg',
      },
      {
        name: 'アンスリア',
        element: '火',
        race: '獸耳',
        weapon: ['格鬥'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040103000_01.jpg',
      },
      {
        name: 'アルルメイヤ(クリスマス)',
        element: '水',
        race: '矮人',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040104000_01.jpg',
      },
      {
        name: 'ルシオ',
        element: '光',
        race: '星晶獸',
        weapon: ['刀','劍'],
        type: '平衡',
        gender: '男',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040106000_01.jpg',
      },
      {
        name: 'ユイシス',
        element: '風',
        race: '獸耳',
        weapon: ['劍','刀'],
        type: '平衡',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040105000_01.jpg',
      },
      {
        name: 'マキラ',
        element: '土',
        race: '矮人',
        weapon: ['樂器'],
        type: '特殊',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040107000_01.jpg',
      },
      {
        name: 'マルキアレス',
        element: '暗',
        race: '矮人',
        weapon: ['杖'],
        type: '特殊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040108000_01.jpg',
      },
      {
        name: 'ラスティナ',
        element: '土',
        race: '牛族',
        weapon: ['槍','銃'],
        type: '防禦',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040109000_01.jpg',
      },
      {
        name: 'ベアトリクス(水着)',
        element: '火',
        race: '人族',
        weapon: ['劍'],
        type: '特殊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040110000_01.jpg',
      },
      {
        name: 'オーキス',
        element: '暗',
        race: '不明',
        weapon: ['格鬥'],
        type: '特殊',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040111000_01.jpg',
      },
      {
        name: 'ゼタ(暗)',
        element: '暗',
        race: '人族',
        weapon: ['槍'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040112000_01.jpg',
      },
      {
        name: 'レ・フィーエ',
        element: '土',
        race: '人族',
        weapon: ['劍'],
        type: '回復',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040113000_01.jpg',
      },
      {
        name: 'スツルム',
        element: '火',
        race: '牛族',
        weapon: ['劍'],
        type: '攻擊',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040115000_01.jpg',
      },
      {
        name: 'キャタピラとヴィーラ',
        element: '水',
        race: '不明',
        weapon: ['銃','格鬥'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040116000_01.jpg',
      },
      {
        name: 'ヴェイン',
        element: '水',
        race: '人族',
        weapon: ['槍','斧'],
        type: '防禦',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040117000_01.jpg',
      },
      {
        name: 'カタリナ',
        element: '暗',
        race: '人族',
        weapon: ['劍'],
        type: '平衡',
        gender: '女',
        get: '特別',
        show: true,
        own: false,
        img: 'img/3040118000_01.jpg',
      },
      {
        name: 'ドランク',
        element: '水',
        race: '獸耳',
        weapon: ['杖'],
        type: '特殊',
        gender: '男',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040119000_01.jpg',
      },
      {
        name: 'カリオストロ(暗)',
        element: '暗',
        race: '人族',
        weapon: ['杖'],
        type: '回復',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040120000_01.jpg',
      },
      {
        name: 'クラリス(光)',
        element: '光',
        race: '人族',
        weapon: ['杖'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040121000_01.jpg',
      },
      {
        name: 'スカーサハ',
        element: '風',
        race: '獸耳',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040122000_01.jpg',
      },
      {
        name: 'メドゥーサ',
        element: '土',
        race: '星晶獸',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '女',
        get: '特別',
        show: true,
        own: false,
        img: 'img/3040123000_01.jpg',
      },
      {
        name: 'バウタオーダ',
        element: '光',
        race: '牛族',
        weapon: ['劍'],
        type: '防禦',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040124000_01.jpg',
      },
      {
        name: 'ユグドラシル',
        element: '土',
        race: '星晶獸',
        weapon: ['格鬥'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040125000_01.jpg',
      },
      {
        name: 'コルワ(水着)',
        element: '風',
        race: '獸耳',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040127000_01.jpg',
      },
      {
        name: 'イシュミール(水着)',
        element: '水',
        race: '牛族',
        weapon: ['劍'],
        type: '攻擊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040126000_01.jpg',
      },
      {
        name: 'ジークフリート(浴衣)',
        element: '風',
        race: '人族',
        weapon: ['劍','刀'],
        type: '攻擊',
        gender: '男',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040128000_01.jpg',
      },
      {
        name: 'ディアンサ(水着)',
        element: '水',
        race: '人族',
        weapon: ['樂器'],
        type: '特殊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040129000_01.jpg',
      },
      {
        name: 'グレア',
        element: '火',
        race: '不明',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040130000_01.jpg',
      },
      {
        name: '三日月宗近',
        element: '光',
        race: '不明',
        weapon: ['刀'],
        type: '平衡',
        gender: '男',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040131000_01.jpg',
      },
      {
        name: 'アン',
        element: '水',
        race: '人族',
        weapon: ['槍'],
        type: '防禦',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040132000_01.jpg',
      },
      {
        name: 'ニーナ・ドランゴ',
        element: '火',
        race: '不明',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '女',
        get: '特別',
        show: true,
        own: false,
        img: 'img/3040133000_01.jpg',
      },
      {
        name: 'サーヴァンツ ドロシー＆クラウディア',
        element: '光',
        race: '人族',
        weapon: ['銃','格鬥'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040134000_01.jpg',
      },
      {
        name: 'アザゼル',
        element: '暗',
        race: '星晶獸',
        weapon: ['短劍','格鬥'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040137000_01.jpg',
      },
      {
        name: 'ダヌア(ハロウィン)',
        element: '火',
        race: '牛族',
        weapon: ['短劍'],
        type: '特殊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040135000_01.jpg',
      },
      {
        name: '木之本桜',
        element: '光',
        race: '人族',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040136000_01.jpg',
      },
      {
        name: 'ユエル(水)',
        element: '水',
        race: '獸耳',
        weapon: ['劍','刀'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040138000_01.jpg',
      },
      {
        name: 'ヴィーラ(光)',
        element: '光',
        race: '星晶獸',
        weapon: ['斧'],
        type: '防禦',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040141000_01.jpg',
      },
      {
        name: 'ランスロット(風)',
        element: '風',
        race: '人族',
        weapon: ['劍','短劍'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040140000_01.jpg',
      },
      {
        name: 'リヴァイ',
        element: '風',
        race: '人族',
        weapon: ['劍','刀'],
        type: '攻擊',
        gender: '男',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040142000_01.jpg',
      },
      {
        name: 'マリー(クリスマス)',
        element: '光',
        race: '人族',
        weapon: ['銃'],
        type: '平衡',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040143000_01.jpg',
      },
      {
        name: 'シャリオス17世',
        element: '火',
        race: '人族',
        weapon: ['劍'],
        type: '特殊',
        gender: '男',
        get: '特別',
        show: true,
        own: false,
        img: 'img/3040144000_01.jpg',
      },
      {
        name: 'オリヴィエ',
        element: '暗',
        race: '星晶獸',
        weapon: ['劍'],
        type: '特殊',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040145000_01.jpg',
      },
      {
        name: 'バザラガ(土)',
        element: '土',
        race: '牛族',
        weapon: ['斧'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040146000_01.jpg',
      },
      {
        name: 'イルザ',
        element: '土',
        race: '獸耳',
        weapon: ['銃','弓'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040148000_01.jpg',
      },
      {
        name: 'ヴァジラ',
        element: '水',
        race: '獸耳',
        weapon: ['刀'],
        type: '攻擊',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040147000_01.jpg',
      },
      {
        name: 'テレーズ',
        element: '火',
        race: '人族',
        weapon: ['劍'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040149000_01.jpg',
      },
      {
        name: 'ゾーイ(銃)',
        element: '光',
        race: '星晶獸',
        weapon: ['銃'],
        type: '平衡',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040150000_01.jpg',
      },
      {
        name: 'メドゥーサ(バレンタイン)',
        element: '土',
        race: '星晶獸',
        weapon: ['格鬥'],
        type: '平衡',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040151000_01.jpg',
      },
      {
        name: 'ティアマト',
        element: '風',
        race: '星晶獸',
        weapon: ['格鬥'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040152000_01.jpg',
      },
      {
        name: '	サンダルフォン',
        element: '光',
        race: '星晶獸',
        weapon: ['劍','刀'],
        type: '平衡',
        gender: '男',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040153000_01.jpg',
      },
      {
        name: 'ジャンヌダルク(水着)',
        element: '風',
        race: '人族',
        weapon: ['劍'],
        type: '平衡',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040154000_01.jpg',
      },
      {
        name: 'ロボミ',
        element: '光',
        race: '不明',
        weapon: ['銃'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040155000_01.jpg',
      },
      {
        name: 'シロウ',
        element: '暗',
        race: '人族',
        weapon: ['刀'],
        type: '防禦',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040156000_01.jpg',
      },
      {
        name: '江戸川コナン',
        element: '光',
        race: '人族',
        weapon: ['銃','格鬥'],
        type: '特殊',
        gender: '男',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040157000_01.jpg',
      },
      {
        name: 'ブローディア',
        element: '土',
        race: '星晶獸',
        weapon: ['劍','刀'],
        type: '防禦',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040158000_01.jpg',
      },
      {
        name: 'ククル',
        element: '水',
        race: '人族',
        weapon: ['銃'],
        type: '平衡',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040159000_01.jpg',
      },
      {
        name: 'ソリッズ',
        element: '土',
        race: '人族',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040170000_01.jpg',
      },
      {
        name: 'カイン',
        element: '土',
        race: '人族',
        weapon: ['刀'],
        type: '特殊',
        gender: '男',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040171000_01.jpg',
      },
      {
        name: 'ルナール',
        element: '暗',
        race: '矮人',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040172000_01.jpg',
      },
      {
        name: 'ジョーカー',
        element: '暗',
        race: '人族',
        weapon: ['短劍','銃'],
        type: '特殊',
        gender: '男',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040173000_01.jpg',
      },
      {
        name: 'ウーフとレニー',
        element: '暗',
        race: '不明',
        weapon: ['格鬥','銃'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040174000_01.jpg',
      },
      {
        name: 'セレフィラ',
        element: '風',
        race: '獸耳',
        weapon: ['樂器'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040175000_01.jpg',
      },
      {
        name: 'ロゼッタ(水着)',
        element: '土',
        race: '星晶獸',
        weapon: ['短劍'],
        type: '特殊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040176000_01.jpg',
      },
      {
        name: 'イルザ(水着)',
        element: '火',
        race: '獸耳',
        weapon: ['銃','弓'],
        type: '攻擊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040177000_01.jpg',
      },
      {
        name: 'ノイシュ(水着)',
        element: '光',
        race: '人族',
        weapon: ['槍'],
        type: '防禦',
        gender: '男',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040178000_01.jpg',
      },
      {
        name: '桜内梨子＆高海千歌＆渡辺 曜',
        element: '水',
        race: '人族',
        weapon: ['劍','銃'],
        type: '平衡',
        gender: '女',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040183000_01.jpg',
      },
      {
        name: '津島善子＆国木田花丸＆黒澤ルビィ',
        element: '土',
        race: '人族',
        weapon: ['杖'],
        type: '回復',
        gender: '女',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040184000_01.jpg',
      },
      {
        name: '松浦果南＆黒澤ダイヤ＆小原鞠莉',
        element: '火',
        race: '人族',
        weapon: ['槍','銃'],
        type: '防禦',
        gender: '女',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040185000_01.jpg',
      },
      {
        name: 'グレア(水着)',
        element: '水',
        race: '不明',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040179000_01.jpg',
      },
      {
        name: 'フォリア',
        element: '水',
        race: '獸耳',
        weapon: ['杖','格鬥'],
        type: '特殊',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040181000_01.jpg',
      },
      {
        name: 'ツバサ',
        element: '火',
        race: '人族',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040180000_01.jpg',
      },
      {
        name: 'フーちゃん',
        element: '暗',
        race: '獸耳',
        weapon: ['銃'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040182000_01.jpg',
      },
      {
        name: 'シルヴァ(光)',
        element: '光',
        race: '人族',
        weapon: ['銃'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040187000_01.jpg',
      },
      {
        name: 'プリキュア',
        element: '光',
        race: '人族',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '女',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040188000_01.jpg',
      },
      {
        name: 'レディ・グレイ(ハロウィン)',
        element: '暗',
        race: '人族',
        weapon: ['槍','格鬥'],
        type: '特殊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040189000_01.jpg',
      },
      {
        name: 'モニカ',
        element: '風',
        race: '人族',
        weapon: ['劍','刀'],
        type: '平衡',
        gender: '女',
        get: '特別',
        show: true,
        own: false,
        img: 'img/3040186000_01.jpg',
      },
      {
        name: 'エウロペ',
        element: '水',
        race: '星晶獸',
        weapon: ['杖'],
        type: '回復',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040190000_01.jpg',
      },
      {
        name: '白竜の双騎士 ランスロット&ヴェイン',
        element: '火',
        race: '人族',
        weapon: ['劍','槍'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040191000_01.jpg',
      },
      {
        name: 'アグロヴァル',
        element: '水',
        race: '人族',
        weapon: ['劍'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040192000_01.jpg',
      },
      {
        name: 'レヴィオン姉妹 マイム＆ミイム＆メイム',
        element: '光',
        race: '人族',
        weapon: ['劍','格鬥'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040193000_01.jpg',
      },
      {
        name: 'ユリウス',
        element: '風',
        race: '人族',
        weapon: ['劍','杖'],
        type: '特殊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040199000_01.jpg',
      },
      {
        name: 'シャルロッテ(光)',
        element: '光',
        race: '矮人',
        weapon: ['劍'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040194000_01.jpg',
      },
      {
        name: 'ペコリーヌ',
        element: '光',
        race: '人族',
        weapon: ['劍'],
        type: '防禦',
        gender: '女',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040200000_01.jpg',
      },
      {
        name: 'コッコロ',
        element: '風',
        race: '不明',
        weapon: ['槍'],
        type: '平衡',
        gender: '女',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040201000_01.jpg',
      },
      {
        name: 'メーテラ(クリスマス)',
        element: '光',
        race: '獸耳',
        weapon: ['弓'],
        type: '平衡',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040195000_01.jpg',
      },
      {
        name: 'シヴァ',
        element: '火',
        race: '星晶獸',
        weapon: ['槍','杖'],
        type: '攻擊',
        gender: '男',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040196000_01.jpg',
      },
      {
        name: 'クビラ',
        element: '光',
        race: '牛族',
        weapon: ['槍','斧'],
        type: '攻擊',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040197000_01.jpg',
      },
      {
        name: 'ユーステス(暗)',
        element: '暗',
        race: '獸耳',
        weapon: ['銃','短劍'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040198000_01.jpg',
      },
      {
        name: 'アテナ',
        element: '火',
        race: '星晶獸',
        weapon: ['槍'],
        type: '防禦',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040202000_01.jpg',
      },
      {
        name: 'ターニャ',
        element: '暗',
        race: '人族',
        weapon: ['短劍'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040203000_01.jpg',
      },
      {
        name: 'セン',
        element: '風',
        race: '獸耳',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040204000_01.jpg',
      },
      {
        name: 'ダーント&フライハイト',
        element: '土',
        race: '人族',
        weapon: ['杖','格鬥'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040205000_01.jpg',
      },
      {
        name: 'クラリス(バレンタイン)',
        element: '暗',
        race: '人族',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040206000_01.jpg',
      },
      {
        name: 'メリッサベル(バレンタイン)',
        element: '光',
        race: '矮人',
        weapon: ['劍','斧'],
        type: '防禦',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040207000_01.jpg',
      },
      {
        name: 'フェリ(暗)',
        element: '暗',
        race: '獸耳',
        weapon: ['短劍'],
        type: '特殊',
        gender: '女',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040209000_01.jpg',
      },
      {
        name: 'ヘルエス(風)',
        element: '風',
        race: '獸耳',
        weapon: ['槍'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040208000_01.jpg',
      },
      {
        name: 'マリア・テレサ',
        element: '水',
        race: '牛族',
        weapon: ['劍','杖'],
        type: '平衡',
        gender: '女',
        get: '十賢者',
        show: true,
        own: false,
        img: 'img/3040160000_01.jpg',
      },
      {
        name: 'カイム',
        element: '土',
        race: '人族',
        weapon: ['短劍','格鬥'],
        type: '特殊',
        gender: '男',
        get: '十賢者',
        show: true,
        own: false,
        img: 'img/3040164000_01.jpg',
      },
      {
        name: 'ニーア',
        element: '暗',
        race: '獸耳',
        weapon: ['短劍','斧'],
        type: '特殊',
        gender: '女',
        get: '十賢者',
        show: true,
        own: false,
        img: 'img/3040169000_01.jpg',
      },
      {
        name: 'エスタリオラ',
        element: '風',
        race: '矮人',
        weapon: ['杖'],
        type: '特殊',
        gender: '男',
        get: '十賢者',
        show: true,
        own: false,
        img: 'img/3040163000_01.jpg',
      },
      {
        name: 'フラウ',
        element: '火',
        race: '獸耳',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '女',
        get: '十賢者',
        show: true,
        own: false,
        img: 'img/3040161000_01.jpg',
      },
      {
        name: 'ロベリア',
        element: '土',
        race: '人族',
        weapon: ['杖','格鬥'],
        type: '攻擊',
        gender: '男',
        get: '十賢者',
        show: true,
        own: false,
        img: 'img/3040165000_01.jpg',
      },
      {
        name: 'ガイゼンボーガ',
        element: '光',
        race: '牛族',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '男',
        get: '十賢者',
        show: true,
        own: false,
        img: 'img/3040162000_01.jpg',
      },
      {
        name: 'ハーゼリーラ',
        element: '水',
        race: '矮人',
        weapon: ['杖','格鬥'],
        type: '特殊',
        gender: '女',
        get: '十賢者',
        show: true,
        own: false,
        img: 'img/3040168000_01.jpg',
      },
      {
        name: 'アラナン',
        element: '火',
        race: '獸耳',
        weapon: ['杖'],
        type: '攻擊',
        gender: '男',
        get: '十賢者',
        show: true,
        own: false,
        img: 'img/3040167000_01.jpg',
      },
      {
        name: 'カッツェリーラ',
        element: '風',
        race: '矮人',
        weapon: ['樂器'],
        type: '防禦',
        gender: '男',
        get: '十賢者',
        show: true,
        own: false,
        img: 'img/3040166000_01.jpg',
      },
      {
        name: 'ユエル(水着)',
        element: '風',
        race: '獸耳',
        weapon: ['劍','刀'],
        type: '平衡',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040210000_01.jpg',
      },
      {
        name: 'ヴィーラ(風)',
        element: '風',
        race: '人族',
        weapon: ['格鬥','樂器'],
        type: '攻擊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040211000_01.jpg',
      },
      {
        name: 'グリームニル',
        element: '風',
        race: '星晶獸',
        weapon: ['槍','杖'],
        type: '平衡',
        gender: '男',
        get: 'Fes限',
        show: true,
        own: false,
        img: 'img/3040212000_01.jpg',
      },
      {
        name: 'マキュラ・マリウス',
        element: '水',
        race: '星晶獸',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040213000_01.jpg',
      },
      {
        name: 'メドゥーサ',
        element: '土',
        race: '星晶獸',
        weapon: ['格鬥'],
        type: '平衡',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040214000_01.jpg',
      },
      {
        name: 'バアル',
        element: '土',
        race: '星晶獸',
        weapon: ['斧','樂器'],
        type: '平衡',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040215000_01.jpg',
      },
      {
        name: 'キャル',
        element: '暗',
        race: '不明',
        weapon: ['杖'],
        type: '攻擊',
        gender: '女',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040216000_01.jpg',
      },
      {
        name: 'ファスティバ',
        element: '土',
        race: '牛族',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '男',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040217000_01.jpg',
      },
      {
        name: 'バイヴカハ',
        element: '風',
        race: '星晶獸',
        weapon: ['杖'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040218000_01.jpg',
      },
      {
        name: 'ルルーシュ・ランペルージ',
        element: '暗',
        race: '人族',
        weapon: ['銃'],
        type: '平衡',
        gender: '男',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040219000_01.jpg',
      },
      {
        name: '枢木スザク',
        element: '風',
        race: '人族',
        weapon: ['劍','格鬥'],
        type: '攻擊',
        gender: '男',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040220000_01.jpg',
      },
      {
        name: '紅月カレン',
        element: '火',
        race: '人族',
        weapon: ['格鬥'],
        type: '攻擊',
        gender: '女',
        get: '活動',
        show: true,
        own: false,
        img: 'img/3040221000_01.jpg',
      },
      {
        name: 'コルル',
        element: '暗',
        race: '人族',
        weapon: ['槍'],
        type: '特殊',
        gender: '女',
        get: '恒常',
        show: true,
        own: false,
        img: 'img/3040222000_01.jpg',
      },
      {
        name: 'ハールート･マールート',
        element: '光',
        race: '星晶獸',
        weapon: ['短劍'],
        type: '平衡',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040223000_01.jpg',
      },
      {
        name: 'サンダルフォン(水着)',
        element: '水',
        race: '星晶獸',
        weapon: ['劍','刀'],
        type: '平衡',
        gender: '男',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040224000_01.jpg',
      },
      {
        name: 'カリオストロ(水着)',
        element: '水',
        race: '人族',
        weapon: ['杖'],
        type: '回復',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040225000_01.jpg',
      },
      {
        name: 'エウロペ(水着)',
        element: '水',
        race: '星晶獸',
        weapon: ['杖'],
        type: '平衡',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040226000_01.jpg',
      },
      {
        name: 'ジェシカ(浴衣)',
        element: '土',
        race: '人族',
        weapon: ['銃'],
        type: '回復',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040227000_01.jpg',
      },
      {
        name: 'アンスリア(浴衣)',
        element: '暗',
        race: '獸耳',
        weapon: ['格鬥'],
        type: '平衡',
        gender: '女',
        get: '季節限定',
        show: true,
        own: false,
        img: 'img/3040228000_01.jpg',
      },
    ]
  },
  computed:{
    fire(){
      var self = this;
      var fireC = [];
    //   篩出火屬
      for(let i=0;i<self.chara.length; i++){
        if(self.chara[i].element == '火'){
          fireC.push(self.chara[i])
        }
      }
    //   filter功能
      for (let i=0; i<fireC.length; i++){
        if (self.filted.race !== '' && self.filted.race !== fireC[i].race){
          fireC[i].show = false
        }else if (self.filted.get !== '' && self.filted.get !== fireC[i].get){
          fireC[i].show = false
        }else if (self.filted.gender !== '' && self.filted.gender !== fireC[i].gender){
          fireC[i].show = false
        }else if (self.filted.weapon !== '' && self.filted.weapon !== fireC[i].weapon[0] && self.filted.weapon !== fireC[i].weapon[1]){
          fireC[i].show = false
        }else if (self.filted.type !== '' && self.filted.type !== fireC[i].type){
          fireC[i].show = false
        }else{
          fireC[i].show = true
        }        
      }      
      return fireC
    },
    water(){
      var self = this;
      var waterC = [];
      for(let i=0;i<self.chara.length; i++){
        if(self.chara[i].element == '水'){
          waterC.push(self.chara[i])
        }
      }
      for (let i=0; i<waterC.length; i++){
        if (self.filted.race !== '' && self.filted.race !== waterC[i].race){
          waterC[i].show = false
        }else if (self.filted.get !== '' && self.filted.get !== waterC[i].get){
          waterC[i].show = false
        }else if (self.filted.gender !== '' && self.filted.gender !== waterC[i].gender){
          waterC[i].show = false
        }else if (self.filted.weapon !== '' && self.filted.weapon !== waterC[i].weapon[0] && self.filted.weapon !== waterC[i].weapon[1]){
          waterC[i].show = false
        }else if (self.filted.type !== '' && self.filted.type !== waterC[i].type){
          waterC[i].show = false
        }else{
          waterC[i].show = true
        }        
      }      
      return waterC
    },
    earth(){
      var self = this;
      var earthC = [];
      for(let i=0;i<self.chara.length; i++){
        if(self.chara[i].element == '土'){
          earthC.push(self.chara[i])
        }
      }
      for (let i=0; i<earthC.length; i++){
        if (self.filted.race !== '' && self.filted.race !== earthC[i].race){
          earthC[i].show = false
        }else if (self.filted.get !== '' && self.filted.get !== earthC[i].get){
          earthC[i].show = false
        }else if (self.filted.gender !== '' && self.filted.gender !== earthC[i].gender){
          earthC[i].show = false
        }else if (self.filted.weapon !== '' && self.filted.weapon !== earthC[i].weapon[0] && self.filted.weapon !== earthC[i].weapon[1]){
          earthC[i].show = false
        }else if (self.filted.type !== '' && self.filted.type !== earthC[i].type){
          earthC[i].show = false
        }else{
          earthC[i].show = true
        }        
      }      
      return earthC
    },
    wind(){
      var self = this;
      var windC = [];
      for(let i=0;i<self.chara.length; i++){
        if(self.chara[i].element == '風'){
          windC.push(self.chara[i])
        }
      }
      for (let i=0; i<windC.length; i++){
        if (self.filted.race !== '' && self.filted.race !== windC[i].race){
          windC[i].show = false
        }else if (self.filted.get !== '' && self.filted.get !== windC[i].get){
          windC[i].show = false
        }else if (self.filted.gender !== '' && self.filted.gender !== windC[i].gender){
          windC[i].show = false
        }else if (self.filted.weapon !== '' && self.filted.weapon !== windC[i].weapon[0] && self.filted.weapon !== windC[i].weapon[1]){
          windC[i].show = false
        }else if (self.filted.type !== '' && self.filted.type !== windC[i].type){
          windC[i].show = false
        }else{
          windC[i].show = true
        }        
      }      
      return windC
    },
    light(){
      var self = this;
      var lightC = [];
      for(let i=0;i<self.chara.length; i++){
        if(self.chara[i].element == '光'){
          lightC.push(self.chara[i])
        }
      }
      for (let i=0; i<lightC.length; i++){
        if (self.filted.race !== '' && self.filted.race !== lightC[i].race){
          lightC[i].show = false
        }else if (self.filted.get !== '' && self.filted.get !== lightC[i].get){
          lightC[i].show = false
        }else if (self.filted.gender !== '' && self.filted.gender !== lightC[i].gender){
          lightC[i].show = false
        }else if (self.filted.weapon !== '' && self.filted.weapon !== lightC[i].weapon[0] && self.filted.weapon !== lightC[i].weapon[1]){
          lightC[i].show = false
        }else if (self.filted.type !== '' && self.filted.type !== lightC[i].type){
          lightC[i].show = false
        }else{
          lightC[i].show = true
        }        
      }      
      return lightC
    },
    dark(){
      var self = this;
      var darkC = [];
      for(let i=0;i<self.chara.length; i++){
        if(self.chara[i].element == '暗'){
          darkC.push(self.chara[i])
        }
      }
      for (let i=0; i<darkC.length; i++){
        if (self.filted.race !== '' && self.filted.race !== darkC[i].race){
          darkC[i].show = false
        }else if (self.filted.get !== '' && self.filted.get !== darkC[i].get){
          darkC[i].show = false
        }else if (self.filted.gender !== '' && self.filted.gender !== darkC[i].gender){
          darkC[i].show = false
        }else if (self.filted.weapon !== '' && self.filted.weapon !== darkC[i].weapon[0] && self.filted.weapon !== darkC[i].weapon[1]){
          darkC[i].show = false
        }else if (self.filted.type !== '' && self.filted.type !== darkC[i].type){
          darkC[i].show = false
        }else{
          darkC[i].show = true
        }        
      }      
      return darkC
    },
    ownpercentage(){
      var self = this;
      let all = self.chara.length;
      let own = 0; 
      for(let i=0; i<self.chara.length; i++){
        if (self.chara[i].own == true){
          own++
        }
      }
      let per = (own/all)*100;
      per = per.toFixed(2)
      return ( own + '/' + all + ' ,　' + per + '%')
    }
  },
  methods:{
    choseGet(item, index){
      var self = this;
      var chosed = item;
      if ( self.filted.get !== chosed ){
        self.filted.get = chosed
      }else{
        self.filted.get = ''
      }
    },
    choseRace: function(item, index){
      var self = this;
      var chosed = item;
      if ( self.filted.race !== chosed.name ){
        self.filted.race = chosed.name
      }else{
        self.filted.race = ''
      }
    },
    choseWeapon(item, index){
      var self = this;
      var chosed = item;
      if ( self.filted.weapon !== chosed.name ){
        self.filted.weapon = chosed.name
      }else{
        self.filted.weapon = ''
      }
    },
    choseType(item, index){
      var self = this;
      var chosed = item;
      if ( self.filted.type !== chosed.name ){
        self.filted.type = chosed.name
      }else{
        self.filted.type = ''
      }
    },
    choseGender(item, index){
      var self = this;
      var chosed = item;
      if ( self.filted.gender !== chosed.name ){
        self.filted.gender = chosed.name
      }else{
        self.filted.gender = ''
      }
    },
    reset(){
      var self = this;
      for (let obj in self.filted){
        self.filted[obj] = ''
      }
      for (let i=0; i<self.filter.element.length; i++){
        self.filter.element[i].active = true
      }
      for (let obj in self.chara){
        self.chara[obj].own = false;
      }
    },
    checkOwnFire(i){
      var self = this;
      this.fire[i].own = true;
    },
    checkOutFire(i){
      var self = this;
      this.fire[i].own = false;
    },
    checkOwnWater(i){
      var self = this;
      this.water[i].own = true;
    },
    checkOutWater(i){
      var self = this;
      this.water[i].own = false;
    },
    checkOwnEarth(i){
      var self = this;
      this.earth[i].own = true;
    },
    checkOutEarth(i){
      var self = this;
      this.earth[i].own = false;
    },
    checkOwnWind(i){
      var self = this;
      this.wind[i].own = true;
    },
    checkOutWind(i){
      var self = this;
      this.wind[i].own = false;
    },
    checkOwnLight(i){
      var self = this;
      this.light[i].own = true;
    },
    checkOutLight(i){
      var self = this;
      this.light[i].own = false;
    },
    checkOwnDark(i){
      var self = this;
      this.dark[i].own = true;
    },
    checkOutDark(i){
      var self = this;
      this.dark[i].own = false;
    },
  }
});